name: hsyn9dhpe
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.8
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pytorch-cuda=11.8
  - numpy=1.24.3
  - matplotlib-base=3.7.2
  - scipy
  - pillow
  - pip
  - pip:
      # OpenMMLab installer
      - openmim>=0.3.2

      # MMPose ecosystem
      - mmengine==0.8.4
      - mmcv==2.1.0
      - mmdet>=3.3.0
      - mmpose>=1.3.0

      # Additional dependencies
      - opencv-python
      - tqdm
      - pyyaml
      - setuptools